### PR TITLE
New service definition: consul_memory

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by eherot** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lAd9PGGZ&#x2F;1234-0-5-address-and-monitor-consul-memory-leak-issue"> (0.5) Address and monitor Consul memory leak issue</a>

**Comment by jeffbyrnes** [comment]
@eherot would love to hear about what that memory leak entails, as I’m probably going to use Consul here at Dark Sky.

**Comment by eherot** [comment]
About the only thing I can tell you is that there is one. I initially suspected that it may have been caused by the fact that we had a stray `vault.json` file hanging around on all of our servers and causing Consul to health check a local port that wasn't serving anything (spewing lots of errors into the logs) but I've since cleaned that up and I'm still seeing an issue on all hosts running Consul.

E.g. When I bounced Consul everywhere at 16:00 UTC on 8/30 it came back online with a memory footprint of 13MB (according to New Relic) and as of right now it's 65MB and climbing at rate of about 1MB per hour.

**Comment by eherot** [comment]
It *might* be related to hashicorp/consul#1718 but I can't explain why because UDP traffic is allowed between all Consul clients.

**Comment by jeffbyrnes** [comment]
@eherot ok, thanks for the breakdown. I’ll keep my peepers peeped when I get Consul up & running.

**Pull request merged**
